In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeClassifier

from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
data_df = pd.read_csv("CancerDataset.csv") 
data_df

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0        0         P1   33       1              2            4             5   
1        1        P10   17       1              3            1             5   
2        2       P100   35       1              4            5             6   
3        3      P1000   37       1              7            7             7   
4        4       P101   46       1              6            8             7   
..     ...        ...  ...     ...            ...          ...           ...   
995    995       P995   44       1              6            7             7   
996    996       P996   37       2              6            8             7   
997    997       P997   25       2              4            5             6   
998    998       P998   18       2              6            8             7   
999    999       P999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                       4             3                     2  ...        3   
1                       3             4                     2  ...        1   
2                       5             5                     4  ...        8   
3                       7             6                     7  ...        4   
4                       7             7                     6  ...        3   
..                    ...           ...                   ...  ...      ...   
995                     7             7                     6  ...        5   
996                     7             7                     6  ...        9   
997                     5             5                     4  ...        8   
998                     7             7                     6  ...        3   
999                     5             5                     4  ...        8   

     Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0              4                    2         2                      3   
1              3                    7         8                      6   
2              7                    9         2                      1   
3              2                    3         1                      4   
4              2                    4         1                      4   
..           ...                  ...       ...                    ...   
995            3                    2         7                      8   
996            6                    5         7                      2   
997            7                    9         2                      1   
998            2                    4         1                      4   
999            7                    9         2                      1   

     Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                           1              2          3        4     Low  
1                           2              1          7        2  Medium  
2                           4              6          7        2    High  
3                           5              6          7        5    High  
4                           2              4          2        3    High  
..                        ...            ...        ...      ...     ...  
995                         2              4          5        3    High  
996                         4              3          1        4    High  
997                         4              6          7        2    High  
998                         2              4          2        3    High  
999                         4              6          7        2    High  

[1000 rows x 26 columns]

In [3]:
X = data_df.drop(columns=["index","Patient Id","Level"])  
y = data_df['Level']

In [4]:
X

Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0     33       1              2            4             5   
1     17       1              3            1             5   
2     35       1              4            5             6   
3     37       1              7            7             7   
4     46       1              6            8             7   
..   ...     ...            ...          ...           ...   
995   44       1              6            7             7   
996   37       2              6            8             7   
997   25       2              4            5             6   
998   18       2              6            8             7   
999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2                       5             5                     4              6   
3                       7             6                     7              7   
4                       7             7                     6              7   
..                    ...           ...                   ...            ...   
995                     7             7                     6              7   
996                     7             7                     6              7   
997                     5             5                     4              6   
998                     7             7                     6              7   
999                     5             5                     4              6   

     Obesity  ...  Coughing of Blood  Fatigue  Weight Loss  \
0          4  ...                  4        3            4   
1          2  ...                  3        1            3   
2          7  ...                  8        8            7   
3          7  ...                  8        4            2   
4          7  ...                  9        3            2   
..       ...  ...                ...      ...          ...   
995        7  ...                  7        5            3   
996        7  ...                  7        9            6   
997        7  ...                  8        8            7   
998        7  ...                  9        3            2   
999        7  ...                  8        8            7   

     Shortness of Breath  Wheezing  Swallowing Difficulty  \
0                      2         2                      3   
1                      7         8                      6   
2                      9         2                      1   
3                      3         1                      4   
4                      4         1                      4   
..                   ...       ...                    ...   
995                    2         7                      8   
996                    5         7                      2   
997                    9         2                      1   
998                    4         1                      4   
999                    9         2                      1   

     Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring  
0                           1              2          3        4  
1                           2              1          7        2  
2                           4              6          7        2  
3                           5              6          7        5  
4                           2              4          2        3  
..                        ...            ...        ...      ...  
995                         2              4          5        3  
996                         4              3          1        4  
997                         4              6          7        2  
998                         2              4          2        3  
999                         4              6          7        2  

[1000 rows x 23 

In [5]:
y

0         Low
1      Medium
2        High
3        High
4        High
        ...  
995      High
996      High
997      High
998      High
999      High
Name: Level, Length: 1000, dtype: object

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [10]:
lasso_model = LogisticRegression(penalty='l1', solver='saga', max_iter=1000)

lasso_model.fit(X_train, y_train)

y_pred = lasso_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy*100,"%")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 99.2 %
Classification Report:
              precision    recall  f1-score   support

        High       0.99      1.00      0.99        93
         Low       0.99      0.99      0.99        79
      Medium       1.00      0.99      0.99        78

    accuracy                           0.99       250
   macro avg       0.99      0.99      0.99       250
weighted avg       0.99      0.99      0.99       250

Confusion Matrix:
[[93  0  0]
 [ 1 78  0]
 [ 0  1 77]]


C:\anaconda\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
